// import type { Metadata } from "next";
// import { Plus_Jakarta_Sans } from "next/font/google";
// import "./globals.css";
// import { auth } from '@/lib/auth';
// import { store } from "@/app/(redux)/store/store";
// import { Provider as ReduxProvider } from 'react-redux';
// // import { QueryClient, QueryClientProvider } from 'react-query';
// import { SessionProvider } from "next-auth/react";

// const JakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "ilevent",
//   description: "Generated by create next app",
//   icons: {
//     icon: '/favicon.ico',
//   },
// };

// // Create a client
// // const queryClient = new QueryClient();

// export default async function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const session = await auth();

//   return (
//     <html lang="en">
//       <body className={JakartaSans.className}>
//         <ReduxProvider store={store}>
//           {/* <QueryClientProvider client={queryClient}> */}
//             <SessionProvider session={session}>
//               {children}
//             </SessionProvider>
//           {/* </QueryClientProvider> */}
//         </ReduxProvider>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import ReduxProvider from './ReduxProvider';
import { AuthProvider } from "@/context/AuthContext";

const JakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ilevent",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={JakartaSans.className}>
        <AuthProvider>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html >
  );
}